controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    both_arms_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    both_arms_head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    both_arms_torso_head_controller:
      type: joint_trajectory_controller/JointTrajectoryController

left_arm_controller:
  ros__parameters:
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
    write_op_modes:
      - position
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_arm_controller:
  ros__parameters:
    joints:
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
    write_op_modes:
      - position
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

both_arms_controller:
  ros__parameters:
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
    write_op_modes:
      - position
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

both_arms_head_controller:
  ros__parameters:
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - head_0
      - head_1
    write_op_modes:
      - position
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

both_arms_torso_head_controller:
  ros__parameters:
    joints:
      - left_arm_0
      - left_arm_1
      - left_arm_2
      - left_arm_3
      - left_arm_4
      - left_arm_5
      - left_arm_6
      - right_arm_0
      - right_arm_1
      - right_arm_2
      - right_arm_3
      - right_arm_4
      - right_arm_5
      - right_arm_6
      - head_0
      - head_1
      - torso_0
      - torso_1
      - torso_2
      - torso_3
      - torso_4
      - torso_5
    write_op_modes:
      - position
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
